plugins { id 'com.android.application' }

android {
    namespace 'com.anarrayaneh.invoice'
    compileSdk 35
    defaultConfig {
        applicationId 'com.hesabyar.app'
        minSdk 29
        targetSdk 35
        versionCode 2
        versionName '1.0.1-mvp'
    }
    buildTypes { release { minifyEnabled false } }
}
