package com.anarrayaneh.invoice;

import android.app.*;
import android.os.*;
import android.provider.MediaStore;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.text.InputType;
import android.util.Base64;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

public class ProInvoiceActivity extends Activity {
    static final int CHERRY=Color.rgb(128,14,39), DARK=Color.rgb(84,8,25), GOLD=Color.rgb(210,157,45), BG=Color.rgb(250,246,244);
    EditText no,date,customer,phone,address,notes,discount; LinearLayout rows; final ArrayList<Row> items=new ArrayList<>(); Bitmap logo;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(DARK);getWindow().setNavigationBarColor(DARK);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);byte[] z=Base64.decode(MainActivity.LOGO,Base64.DEFAULT);logo=BitmapFactory.decodeByteArray(z,0,z.length);setContentView(screen());}
    View screen(){ScrollView s=new ScrollView(this);LinearLayout r=v();r.setPadding(dp(14),dp(14),dp(14),dp(30));r.setBackgroundColor(BG);s.addView(r);LinearLayout h=h();h.setPadding(dp(12),dp(12),dp(12),dp(12));h.setBackground(round(DARK,18));ImageView im=new ImageView(this);im.setImageBitmap(logo);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);h.addView(im,new LinearLayout.LayoutParams(dp(88),dp(88)));LinearLayout ht=v();ht.addView(txt("فاکتور انار رایانه",24,Color.WHITE,true));ht.addView(txt("خروجی رسمی آلبالویی و طلایی",13,Color.rgb(245,220,225),false));h.addView(ht,new LinearLayout.LayoutParams(0,-2,1));r.addView(h);
        r.addView(sec("مشخصات فاکتور"));no=ed("شماره فاکتور",2);no.setText(defaultNo());date=ed("تاریخ شمسی",1);date.setText(jalaliToday());customer=ed("نام مشتری / شرکت",1);phone=ed("شماره تماس مشتری",3);address=ed("آدرس مشتری",1);r.addView(no);r.addView(date);r.addView(customer);r.addView(phone);r.addView(address);
        r.addView(sec("کالا و خدمات"));rows=v();r.addView(rows);addRow();Button add=btn("+ افزودن ردیف",GOLD);add.setOnClickListener(v->{if(items.size()<10)addRow();});r.addView(add);
        r.addView(sec("محاسبات و توضیحات"));discount=ed("تخفیف (تومان)",2);notes=ed("توضیحات فاکتور (اختیاری)",1);notes.setMinLines(2);r.addView(discount);r.addView(notes);
        LinearLayout a=h();Button pv=btn("پیش‌نمایش",DARK),pdf=btn("ذخیره PDF",CHERRY),png=btn("ذخیره عکس",GOLD);a.addView(pv,w());a.addView(pdf,w());a.addView(png,w());r.addView(a);pv.setOnClickListener(v->preview());pdf.setOnClickListener(v->save(true));png.setOnClickListener(v->save(false));TextView f=txt("لوگوی شرکت در سربرگ، واترمارک و بخش مهر ثبت می‌شود",12,Color.DKGRAY,false);f.setGravity(Gravity.CENTER);r.addView(f);return s;}
    void addRow(){LinearLayout c=v();c.setPadding(dp(8),dp(8),dp(8),dp(8));c.setBackground(round(Color.WHITE,12));EditText d=ed("شرح کالا / خدمت",1),q=ed("تعداد",2),p=ed("قیمت واحد (تومان)",2);q.setText("1");LinearLayout n=h();n.addView(q,w());n.addView(p,w());c.addView(d);c.addView(n);Button x=btn("حذف",Color.rgb(150,55,65));c.addView(x);Row rr=new Row(c,d,q,p);items.add(rr);x.setOnClickListener(v->{if(items.size()>1){items.remove(rr);rows.removeView(c);}else{d.setText("");q.setText("1");p.setText("");}});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(8));rows.addView(c,lp);}
    InvoiceData data(){InvoiceData d=new InvoiceData();d.number=no.getText().toString().trim();d.date=date.getText().toString().trim();d.customer=customer.getText().toString().trim();d.phone=phone.getText().toString().trim();d.address=address.getText().toString().trim();d.notes=notes.getText().toString().trim();d.discount=money(discount.getText().toString());if(d.number.isEmpty()||d.customer.isEmpty()){toast("شماره فاکتور و نام مشتری را وارد کنید.");return null;}for(Row r:items){String s=r.d.getText().toString().trim();double q=num(r.q.getText().toString());long p=money(r.p.getText().toString());if(!s.isEmpty()&&q>0){InvoiceData.Item it=new InvoiceData.Item();it.description=s;it.quantity=q;it.unitPrice=p;it.total=Math.round(q*p);d.items.add(it);d.sum+=it.total;}}if(d.items.isEmpty()){toast("حداقل یک ردیف کالا یا خدمت وارد کنید.");return null;}if(d.discount>d.sum)d.discount=d.sum;d.total=d.sum-d.discount;return d;}
    Bitmap render(InvoiceData d){InvoiceTemplateView v=new InvoiceTemplateView(this,d,logo);v.measure(View.MeasureSpec.makeMeasureSpec(InvoiceTemplateView.BASE_W,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(InvoiceTemplateView.BASE_H,View.MeasureSpec.EXACTLY));v.layout(0,0,InvoiceTemplateView.BASE_W,InvoiceTemplateView.BASE_H);Bitmap b=Bitmap.createBitmap(InvoiceTemplateView.BASE_W,InvoiceTemplateView.BASE_H,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);v.draw(c);return b;}
    void preview(){InvoiceData d=data();if(d==null)return;ImageView im=new ImageView(this);im.setImageBitmap(render(d));im.setAdjustViewBounds(true);im.setPadding(dp(6),dp(6),dp(6),dp(6));ScrollView s=new ScrollView(this);s.addView(im);new AlertDialog.Builder(this).setTitle("پیش‌نمایش فاکتور").setView(s).setPositiveButton("بستن",null).show();}
    void save(boolean pdf){InvoiceData d=data();if(d==null)return;Bitmap b=render(d);String base="AnarRayaneh_"+norm(d.number).replaceAll("[^0-9A-Za-z_-]","_");try{ContentResolver cr=getContentResolver();ContentValues cv=new ContentValues();Uri u;if(pdf){cv.put(MediaStore.Downloads.DISPLAY_NAME,base+".pdf");cv.put(MediaStore.Downloads.MIME_TYPE,"application/pdf");cv.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/AnarRayaneh");u=cr.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,cv);PdfDocument pd=new PdfDocument();PdfDocument.Page page=pd.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());page.getCanvas().drawBitmap(b,null,new Rect(0,0,595,842),new Paint(Paint.ANTI_ALIAS_FLAG));pd.finishPage(page);OutputStream o=cr.openOutputStream(u);pd.writeTo(o);o.close();pd.close();toast("PDF رسمی در Downloads/AnarRayaneh ذخیره شد.");}else{cv.put(MediaStore.Images.Media.DISPLAY_NAME,base+".png");cv.put(MediaStore.Images.Media.MIME_TYPE,"image/png");cv.put(MediaStore.Images.Media.RELATIVE_PATH,Environment.DIRECTORY_PICTURES+"/AnarRayaneh");u=cr.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,cv);OutputStream o=cr.openOutputStream(u);b.compress(Bitmap.CompressFormat.PNG,100,o);o.close();toast("عکس فاکتور در Pictures/AnarRayaneh ذخیره شد.");}}catch(Exception e){toast("خطا در ذخیره: "+e.getMessage());}}
    EditText ed(String hint,int type){EditText e=new EditText(this);e.setHint(hint);e.setGravity(Gravity.RIGHT);e.setTextSize(15);e.setPadding(dp(10),dp(10),dp(10),dp(10));e.setBackground(round(Color.WHITE,10));e.setInputType(type==2?InputType.TYPE_CLASS_NUMBER:type==3?InputType.TYPE_CLASS_PHONE:InputType.TYPE_CLASS_TEXT);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));e.setLayoutParams(lp);return e;} TextView sec(String s){TextView t=txt(s,17,DARK,true);t.setPadding(0,dp(15),0,dp(6));return t;} Button btn(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(round(c,10));return b;} TextView txt(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT);t.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));t.setPadding(dp(8),dp(8),dp(8),dp(8));return t;} LinearLayout v(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return l;} LinearLayout h(){LinearLayout l=v();l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;} LinearLayout.LayoutParams w(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(54),1);p.setMargins(dp(3),dp(5),dp(3),dp(5));return p;} GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    long money(String s){try{return Long.parseLong(norm(s).replace(",","").replace("٬","").trim());}catch(Exception e){return 0;}} double num(String s){try{return Double.parseDouble(norm(s).replace("٫",".").trim());}catch(Exception e){return 0;}}String norm(String s){String f="۰۱۲۳۴۵۶۷۸۹",a="٠١٢٣٤٥٦٧٨٩";for(int i=0;i<10;i++){s=s.replace(f.charAt(i),(char)('0'+i));s=s.replace(a.charAt(i),(char)('0'+i));}return s;}String defaultNo(){return jalaliToday().substring(0,4)+"-0001";}
    String jalaliToday(){Calendar c=Calendar.getInstance();int gy=c.get(Calendar.YEAR),gm=c.get(Calendar.MONTH)+1,gd=c.get(Calendar.DAY_OF_MONTH);int[]j=g2j(gy,gm,gd);return String.format(Locale.US,"%04d/%02d/%02d",j[0],j[1],j[2]);}int[] g2j(int gy,int gm,int gd){int[]d={0,31,59,90,120,151,181,212,243,273,304,334};int gy2=gm>2?gy+1:gy;long days=355666L+365L*gy+(gy2+3)/4-(gy2+99)/100+(gy2+399)/400+gd+d[gm-1];int jy=-1595+33*(int)(days/12053);days%=12053;jy+=4*(int)(days/1461);days%=1461;if(days>365){jy+=(int)((days-1)/365);days=(days-1)%365;}int jm,jd2;if(days<186){jm=1+(int)(days/31);jd2=1+(int)(days%31);}else{jm=7+(int)((days-186)/30);jd2=1+(int)((days-186)%30);}return new int[]{jy,jm,jd2};}
    static class Row{LinearLayout c;EditText d,q,p;Row(LinearLayout c,EditText d,EditText q,EditText p){this.c=c;this.d=d;this.q=q;this.p=p;}}
}
